CREATE TABLE SALES_DETAILS ( ID INTEGER PRIMARY KEY,LATITUDE FLOAT,TRANSACTION_DATE TIMESTAMP,ACCOUNT_CREATED TIMESTAMP,CITY VARCHAR(255),COUNTRY VARCHAR(255),
LAST_LOGIN TIMESTAMP,LONGITUDE FLOAT,NAME VARCHAR(255),PAMENT_TYPE VARCHAR(255),PRICE INT,PRODUCT VARCHAR(255),STATE VARCHAR(255));

